#!/bin/bash

# This is the setup script for my config. The idea is to be able to run
# this after cloning the repo on a Mac or Ubuntu (WSL) system and be up
# and running very quickly.

# create directories
export XDG_CONFIG_HOME="$HOME"/.config
export DOTFILES_DIR="$PWD"
#mkdir -p "$XDG_CONFIG_HOME"/bash
#mkdir -p "$XDG_CONFIG_HOME"/alacritty
#mkdir -p "$XDG_CONFIG_HOME"/alacritty/themes

#mkdir -p "$XDG_CONFIG_HOME"/skhd
#mkdir -p "$XDG_CONFIG_HOME"/k9s
# mkdir -p "$XDG_CONFIG_HOME"/wezterm

#git clone https://github.com/alacritty/alacritty-theme "$XDG_CONFIG_HOME"/alacritty/themes

# Symbolic links

# ln -s ./.amethyst.yml "$HOME"/.amethyst.yml

# ln -sf "$PWD/alacritty.toml" "$XDG_CONFIG_HOME"/alacritty/alacritty.toml

#ln -sf "$PWD/k9s/skin.yml" "$XDG_CONFIG_HOME"/k9s/skin.yml

#ln -sf "$PWD/.bash_profile" "$HOME"/.bash_profile
#ln -sf "$PWD/.bashrc" "$HOME"/.bashrc
#ln -sf "$PWD/.inputrc" "$HOME"/.inputrc
#ln -sf "$PWD/.tmux.conf" "$HOME"/.tmux.conf

#ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim
#ln -sf "$PWD/skhdrc" "$XDG_CONFIG_HOME"/skhd/skhdrc
#ln -sf "$PWD/sway" "$XDG_CONFIG_HOME/sway"
# ln -sf "$PWD/newsboat/config" "$HOME"/.newsboat/config
# ln -sf "$PWD/newsboat/urls" "$HOME"/.newsboat/urls

# Packages

# install brew
# /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# For ubuntu:

mkdir -p $HOME/.local/share/fonts
cp $PWD/fonts/UbuntuMono* $HOME/.local/share/fonts

git clone https://github.com/sindresorhus/pure.git "$HOME/.zsh/pure"
curl -sfL https://direnv.net/install.sh | bash
curl -fsSL https://get.jetify.com/devbox | bash

# brew packages Mac
# amethyst fzf nvim exa hugo bash-completion@2 newsboat kubectl starship
# brew install --cask alacritty

# ubuntu packages apt
# sudo apt install ripgrep gh

# ubuntu apt neovim setup
# sudo apt install gcc g++ unzip

# ubuntu brew for vim and neovim setup
#sudo apt install fd fzf kubectl kubectx
sudo apt install fzf
# curl -sS https://starship.rs/install.sh | sh

# ubuntu brew for neovim setup
# brew install neovim go lazygit

# ubuntu specific notes
# create symbolic link to neovim from vim when not using neovim on
# Ubuntu systems, because I use the v alias everywhere.
# sudo ln -sf /usr/bin/vim /usr/bin/nvim
#

# Fedora

# brew install fd fzf ripgrep

# /usr/bin/python3 -m pip install pynvim

create_directories() {
  local directories=("$@")
  for dir in "${directories[@]}"; do
    mkdir -p "$dir"
  done
}

create_symlinks() {
  local items=("$@")
  for item in "${items[@]}"; do
    IFS=':' read -r source target <<<"$item"
    if [ -L "$target" ]; then
      echo "Removing existing symlink $target"
      unlink "$target"
    elif [ -d "$target" ]; then
      echo "Warning: $target is a directory. Skipping..."
      continue
    elif [ -e "$target" ]; then
      echo "Warning: $target already exists. Skipping..."
      continue
    fi
    ln -s "$DOTFILES_DIR/$source" "$target"
    echo "Created symlink for $source"
  done
}

common_directories=(
  "$XDG_CONFIG_HOME/alacritty"
  "$XDG_CONFIG_HOME/alacritty/themes"
)

common_items=(
  "alacritty.toml:$XDG_CONFIG_HOME/alacritty/alacritty.toml"
  ".inputrc:$HOME/.inputrc"
  ".tmux.conf:$HOME/.tmux.conf"
  "nvim:$XDG_CONFIG_HOME/nvim"
  ".zprofile:$HOME/.zprofile"
  ".zshrc:$HOME/.zshrc"
)

create_directories "${common_directories[@]}"
create_symlinks "${common_items[@]}"
